remote_theme: jekyll/minima@v2.5.2
title: Akıl Terapileri
description: >
  © 2025 Cihan Deniz — CC-BY-4.0
header_pages:
  - yazilar/index.md
  - eskizler/index.md
minima:
  date_format: "%Y-%m-%d %H:%M"
